server:
  servlet:
    context-path:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iprs?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: username
    password: "passwd"