server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iprs?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: "passwd"
  jpa:
    show-sql: true
elasticsearch:
  hostname: localhost
  port: 9200
  index: iprs