package edu.nju.iip.iprs.product.list.constants;

public interface IProdListExceptionConstants
{
    static final String EXCEPTION_NON_EXISTING = "EXCEPTION_HANDLER_NON_EXISTING";
    static final String EXCEPTION_VALUE_LIST_CODE_NOT_EDITABLE = "EXCEPTION_VALUE_LIST_CODE_NOT_EDITABLE";
    static final String EXCEPTION_VALUE_LIST_DATA_TYPE_NOT_EDITABLE = "EXCEPTION_VALUE_LIST_DATA_TYPE_NOT_EDITABLE";
    static final String EXCEPTION_VALUE_LIST_VALUE_NOT_EDITABLE = "EXCEPTION_VALUE_LIST_VALUE_NOT_EDITABLE";
    static final String EXCEPTION_VALUE_LIST_VALUE_NOT_DELETABLE = "EXCEPTION_VALUE_LIST_VALUE_NOT_DELETABLE";
    static final String EXCEPTION_VALUE_LIST_NOT_DELETABLE = "MSG_USED_SINGLE_ITEM_DELETE_EXCEPTION";
    static final String EXCEPTION_VALUE_LIST_IS_PREDEFINED = "MSG_STANDARD_SINGLE_ITEM_SAVE_OR_DELETE_EXCEPTION";
    static final String EXCEPTION_DATA_TYPE_INVALID = "EXCEPTION_DATA_TYPE_INVALID";
}
